### ISSUE TITLE
Option to Show on Local Plex Web

### ISSUE THREAD

**Issue by seanogdev** [danbovey/SonarrPlex#1]
I use the local ip address of Plex to connect, just in case I get connection issues. Adding an option to the config to allow for this would be great!

**Comment by danbovey** [comment]
If you're running Sonarr for Plex 1.0.5, which I'm uploading now, you can add IP addresses and URLs into a new field on the Options page called **Plex URLs**.

If you add `localhost:32400`, `123.456.0.1:12345` etc, it will run the extension when accessing Plex from any of those URLs.
