### ISSUE TITLE
Images don't display with BaseURL in Sonarr

### ISSUE THREAD

**Issue by some-guy-23** [danbovey/SonarrPlex#4]
My Sonarr settings have a baseURL of **/sonarr**

The API calls seem to go through without issue, however none of the images are loading. When I check the URL they are pointed at, it shows "[host]/sonarr/sonarr/MediaCover/64/[image]". So, seems to be putting an extra **/sonarr** in the path. Once I remove that, it loads just fine.

I believe this issue is here - https://github.com/danbovey/SonarrPlex/blob/master/js/poster.js#L84

The series endpoint in Sonarr returns a relative URL which includes the baseURL already. So, it gets doubled up.

**Comment by danbovey** [comment]
Thanks for working that out. I'll have to add an option to tell this extension that you're using a base URL and then replace it out of the start of the relative URL.

**Comment by danbovey** [comment]
@some-guy-23 If you're running Sonarr for Plex 1.0.4, which I'm uploading now, you can go back to the options page and insert your Sonarr's URL base, fixing the poster loading.

`sonarr`, `/sonarr`, or `sonarr/` all work the same way.
