### ISSUE TITLE
Externally hosted Images on Add Series page don't display

### ISSUE THREAD

**Issue by some-guy-23** [danbovey/SonarrPlex#5]
When you do a search to add a new series, it is appending the Sonarr URL to external images (e.g. on TVDB).  This bit of code should probably check for an external site reference - 

https://github.com/danbovey/SonarrPlex/blob/master/js/poster.js#L80

**Comment by danbovey** [comment]
Yep, shouldn't have removed this

https://github.com/danbovey/SonarrPlex/blob/1063de6a648f494c41f29b76f401ae619b26c75f/js/poster.js#L84
