### ISSUE TITLE
addSeries button function is undefined

### ISSUE THREAD

**Issue by tuccle22** [danbovey/SonarrPlex#8]
Hey!  Awesome extension, by the way.

It looks like the openPage function here: https://github.com/danbovey/SonarrPlex/blob/master/js/pages/series.js#L15 is undefined.

This causes the following error in the console: 
Uncaught TypeError: t is not a function
    at HTMLButtonElement.<anonymous>

**Comment by danbovey** [comment]
Fix published in version `1.0.6`.
